### ISSUE TITLE
مشکل در fine tune مدل پارافریز با دیتاستی که ساختم

### ISSUE THREAD

**Issue by mhdi707** [Aliarcher/Natural-Language-Processing#1]
سلام علی آقا روز شما بخیر! میبخشید من با کد finetune  ای که برای پارافریز زدین میخواستم رو دیتاستی که خودم ساختم فاین تیون کنم ولی با اررو زیر مواجه شدم ممنون میشم کمک کنید مشکل از کجاست من max_length=256 قرار دادم هم برای autoTokenizer  هم برای tockenize  input  ها`TypeError                                 Traceback (most recent call last)
<ipython-input-20-1cdd036f44a3> in <cell line: 2>()
      1 print("شروع آموزش...")
----> 2 trainer.train()

12 frames
/usr/lib/python3.10/json/encoder.py in default(self, o)
    177 
    178         """
--> 179         raise TypeError(f'Object of type {o.__class__.__name__} '
    180                         f'is not JSON serializable')
    181 

TypeError: Object of type method is not JSON serializable
`

**Comment by Aliarcher** [comment]
سلام وقت شما هم بخیر، خطای شما رو متوجه نمیشم میتونید یک شمایی از دیتاست و کد رو برام ارسال کنید.
به طور کلی دیتاست های paraphrase به صورت source-text  و target-text  هست در ابتدا سعی کنید فرمت دیتا رو به صورت فرمت huggingface تبدیل کنید سپس آموزش بدهید.
به طور مثال:
DatasetDict({ 
train: Dataset({ features: ['input_text', 'target_text', 'input_ids', 'attention_mask', 'labels'], num_rows: 800 }) 
test: Dataset({ features: ['input_text', 'target_text', 'input_ids', 'attention_mask', 'labels'], num_rows: 200 }) })

**Comment by mhdi707** [comment]
![Screenshot 2023-10-08 102453](https://github.com/Aliarcher/Natural-Language-Processing/assets/124491041/99dc0f48-18ad-4dfd-929b-efb4e64c2321)
سلام ممنون از پاسخگویی ولادقیقا دیتا ست به همون شکلی هست که شما
درhuggingface  قرار دادید .ایمیلتون رو محبت می کنید که دیتاست رو براتون
ارسال کنم من پایان نامه ام در مورد text simplification  هست و میخوام ببینم
با مدل های pretrained t5 تا چه حدی میشه اینکار رو انجام داد در واقع هدف
بنده این هست که بتوانم از جملات پیچیده ،جملات ساده ای رو استخراج کنم که به
هم عطف شده اند.

**Comment by Aliarcher** [comment]
> سلام ممنون از پاسخگویی ولادقیقا دیتا ست به همون شکلی هست که شما
> درhuggingface  قرار دادید .ایمیلتون رو محبت می کنید که دیتاست رو براتون
> ارسال کنم من پایان نامه ام در مورد text simplification  هست و میخوام ببینم
> با مدل های pretrained t5 تا چه حدی میشه اینکار رو انجام داد در واقع هدف
> بنده این هست که بتوانم از جملات پیچیده ،جملات ساده ای رو استخراج کنم که به
> هم عطف شده اند.
> 
> On Sun, Oct 8, 2023 at 9:03 AM Seyed Ali Mir Mohammad Hosseini <

**Comment by Aliarcher** [comment]
بله یکی از راهکار ها همین هست.
اگه دقیقا دیتا به این شکل دراومده مشکل دیتا نیست حالا من جزئیات کدتون و خطا رو نمیدونم اگه کمک دیگه از من ساخته هست
 ایمیل بنده sa.sorb1376@gmail.com هست.

**Comment by Aliarcher** [comment]
مشکل در ورژن transformers هست ورژن آن را پایین بیارید.
